version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
  
  site-vitrine:
    build:
      context: ./site-vitrine
      dockerfile: Dockerfile
    ports:
      - "8081:80"